<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Export_k-icon k-filter</name>
   <tag></tag>
   <elementGuidId>897494e3-e6d1-4b07-a777-2fd512c279b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='RegistrationGrid_NextGate1']/div[2]/div/table/thead/tr/th[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-icon k-filter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegistrationGrid_NextGate1&quot;)/div[@class=&quot;k-grid-header&quot;]/div[@class=&quot;k-grid-header-wrap k-auto-scrollable&quot;]/table[1]/thead[1]/tr[1]/th[@class=&quot;k-header k-filterable k-with-icon k-state-border-down&quot;]/a[@class=&quot;k-grid-filter&quot;]/span[@class=&quot;k-icon k-filter&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RegistrationGrid_NextGate1']/div[2]/div/table/thead/tr/th[2]/a/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/a/span</value>
   </webElementXpaths>
</WebElementEntity>
