<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Export</name>
   <tag></tag>
   <elementGuidId>71b1c9bf-2606-4caa-8ace-08763a00c138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=concat(&quot;sendARWorkdownListExcel('{&quot;,'&quot;System&quot;:&quot;&quot;,&quot;Department&quot;:&quot;&quot;,&quot;Division&quot;:&quot;&quot;,&quot;FinancialClassTypeID&quot;:&quot;&quot;,&quot;AgencyID&quot;:&quot;&quot;,&quot;StartDate&quot;:&quot;&quot;,&quot;Insurance&quot;:&quot;&quot;,&quot;InOut&quot;:&quot;&quot;,&quot;CycleID&quot;:&quot;&quot;,&quot;Provider&quot;:&quot;&quot;,&quot;EndDate&quot;:&quot;&quot;,&quot;IncludeAssigned&quot;:false,&quot;CARC&quot;:[],&quot;RARC&quot;:[],&quot;insurance&quot;:&quot;GUA&quot;,&quot;billingarea&quot;:&quot;BA0000000038&quot;,&quot;range&quot;:&quot;Upto180&quot;}',&quot;')&quot;)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-button k-button-icontext </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>sendARWorkdownListExcel('{&quot;System&quot;:&quot;&quot;,&quot;Department&quot;:&quot;&quot;,&quot;Division&quot;:&quot;&quot;,&quot;FinancialClassTypeID&quot;:&quot;&quot;,&quot;AgencyID&quot;:&quot;&quot;,&quot;StartDate&quot;:&quot;&quot;,&quot;Insurance&quot;:&quot;&quot;,&quot;InOut&quot;:&quot;&quot;,&quot;CycleID&quot;:&quot;&quot;,&quot;Provider&quot;:&quot;&quot;,&quot;EndDate&quot;:&quot;&quot;,&quot;IncludeAssigned&quot;:false,&quot;CARC&quot;:[],&quot;RARC&quot;:[],&quot;insurance&quot;:&quot;GUA&quot;,&quot;billingarea&quot;:&quot;BA0000000038&quot;,&quot;range&quot;:&quot;Upto180&quot;}')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Export</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ARWorkdownInvoicesGrid&quot;)/div[@class=&quot;k-header k-grid-toolbar k-grid-top d-flex align-items-center text-white bg-primary font-weight-bold&quot;]/a[@class=&quot;k-button k-button-icontext&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=concat(&quot;sendARWorkdownListExcel('{&quot;,'&quot;System&quot;:&quot;&quot;,&quot;Department&quot;:&quot;&quot;,&quot;Division&quot;:&quot;&quot;,&quot;FinancialClassTypeID&quot;:&quot;&quot;,&quot;AgencyID&quot;:&quot;&quot;,&quot;StartDate&quot;:&quot;&quot;,&quot;Insurance&quot;:&quot;&quot;,&quot;InOut&quot;:&quot;&quot;,&quot;CycleID&quot;:&quot;&quot;,&quot;Provider&quot;:&quot;&quot;,&quot;EndDate&quot;:&quot;&quot;,&quot;IncludeAssigned&quot;:false,&quot;CARC&quot;:[],&quot;RARC&quot;:[],&quot;insurance&quot;:&quot;GUA&quot;,&quot;billingarea&quot;:&quot;BA0000000038&quot;,&quot;range&quot;:&quot;Upto180&quot;}',&quot;')&quot;)]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ARWorkdownInvoicesGrid']/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Export')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR Workdown'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column Settings'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Export']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/a</value>
   </webElementXpaths>
</WebElementEntity>
