<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Payments</name>
   <tag></tag>
   <elementGuidId>226138d3-3cee-4335-b0fa-11e58d50e8eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ARWorkdownInvoicesGrid']/table/thead/tr/th[15]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k-link k-state-active k-state-border-down</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/DRISDEV/ARWorkdown/InvoicesList?criteriaJson=%7B%22System%22%3A%22%22%2C%22Department%22%3A%22%22%2C%22Division%22%3A%22%22%2C%22FinancialClassTypeID%22%3A%22%22%2C%22AgencyID%22%3A%22%22%2C%22StartDate%22%3A%22%22%2C%22Insurance%22%3A%22%22%2C%22InOut%22%3A%22%22%2C%22CycleID%22%3A%22%22%2C%22Provider%22%3A%22%22%2C%22EndDate%22%3A%22%22%2C%22IncludeAssigned%22%3Afalse%2C%22CARC%22%3A%5B%5D%2C%22RARC%22%3A%5B%5D%2C%22insurance%22%3A%22M01%22%2C%22billingarea%22%3A%22BA0000000050%22%2C%22range%22%3A%22Over180%22%7D&amp;ARWorkdownInvoicesGrid-sort=Payments-asc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payments</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ARWorkdownInvoicesGrid&quot;)/table[1]/thead[@class=&quot;k-grid-header&quot;]/tr[1]/th[@class=&quot;k-header k-with-icon k-state-border-down&quot;]/a[@class=&quot;k-link k-state-active k-state-border-down&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ARWorkdownInvoicesGrid']/table/thead/tr/th[15]/a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Payments')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column Settings'])[15]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Column Settings'])[16]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[1]/preceding::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payments']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/DRISDEV/ARWorkdown/InvoicesList?criteriaJson=%7B%22System%22%3A%22%22%2C%22Department%22%3A%22%22%2C%22Division%22%3A%22%22%2C%22FinancialClassTypeID%22%3A%22%22%2C%22AgencyID%22%3A%22%22%2C%22StartDate%22%3A%22%22%2C%22Insurance%22%3A%22%22%2C%22InOut%22%3A%22%22%2C%22CycleID%22%3A%22%22%2C%22Provider%22%3A%22%22%2C%22EndDate%22%3A%22%22%2C%22IncludeAssigned%22%3Afalse%2C%22CARC%22%3A%5B%5D%2C%22RARC%22%3A%5B%5D%2C%22insurance%22%3A%22M01%22%2C%22billingarea%22%3A%22BA0000000050%22%2C%22range%22%3A%22Over180%22%7D&amp;ARWorkdownInvoicesGrid-sort=Payments-asc')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[15]/a[2]</value>
   </webElementXpaths>
</WebElementEntity>
